@startuml SceneEvents
class SceneEvents {
    ..Events..
    {static} +OnLoadScene
    {static} +OnUnloadScene
    {static} +OnSetSceneActive
    --Invokers--
    {static} +loadScene()
    {static} +unloadScene()
    {static} +setSceneActive()
}
@enduml