@startuml UIEvents
class UIEvents {
    ..Events..
    {static} +OnEnableCanvas
    {static} +OnDisableAllCanvases
    --Invokers--
    {static} +OnEnableCanvas
    {static} +OnDisableAllCanvases
}
@enduml