@startuml inputsystem
!theme reddress-darkblue

class AudioManager {
    {static} +Instance
    -audioMixer
    ---
    -playAudio()
    -stopAudioClip()
    -stopAllAudioInGroup()
    -setVolume()
    -getAudioGroupPool()
    --Object Pooling--
    ..Pools..
    -menuAudioPool
    -gameAudioPool
    -musicAudioPool
    ..Pool Sizes..
    -menuAudioPoolSize
    -gameAudioPoolSize
    -musicAudioPoolSize
    ..Audio Prefabs..
    -menuAudioPrefab
    -gameAudioPrefab
    -musicAudioPrefab
}

class AudioEvents {
    ..Events..
    {static} +OnPlayAudio
    {static} +OnSetVolume
    {static} +OnStopAudioClip
    {static} +OnStopAllAudio
    ---
    ..Invokers..
    {static} +playAudio()
    {static} +setVolume()
    {static} +stopAudioClip()
    {static} +stopAllAudioInGroup()
}

class AudioPool {
    -audioSources
    -audioPoolSize
    -audioPrefab
    -parentTransform
    -initAudioPool()
    +getAvailableAudioSource()
    +getActiveAudioSource()
    +returnAudioToPool()
    +returnAudioSource()
    +returnAllSources()
    +returnAudioSourceWhenFinished()
}

AudioManager       "1..1"    .up.     "1..1"    AudioEvents    : "Listens >"
AudioManager       "1..1"    .down.  "0..*"    AudioPool      : "Has >"

@enduml
