@startuml dpinject
!theme reddress-darkblue

!include GameManager.puml
!include StoreSystem/StoreSystem.puml
!include Pause/PauseSystem.puml
!include Transition/TransitionSystem.puml

GameManager -up- StoreController : "Injects >"
GameManager -up- PauseController : "Injects >"
GameManager -up- TransitionController : "Injects >"
@endluml