@startuml gamestatesystem

class GameStateManager {
    {static} +Instance
    --
    -pauseGame()
    -resumeGame()
    -quitGame()
}

class GameStateEvents {
    ..Events..
    {static} +OnPauseGame
    {static} +OnResumeGame
    --Invokers--
    {static} +PauseGame()
    {static} +ResumeGame()
}

GameStateManager    "1..1"   .up.     "1..1"   GameStateEvents   : "Listens >"

@enduml