@startuml inputsystem

class InputManager {
    {static} +Instance
    -PlayerInput
    -playerInputHandler
    -pausedInputHandler
    --
    -enableActionMap()
    -disableActionMap()
}

class InputEvents {
    ..Events..
    {static} +OnEnableActionMap
    {static} +OnDisableActionMap
    --Invokers--
    {static} +EnableActionMap()
    {static} +DisableActionMap()
}

abstract InputHandler {
    #playerInput
}

class PlayerInputHandler {
    +OnPause()
}

class PauseMenuInputHandler {
    +OnResume()
}

class StoreMenuInputHandler {
    +OnExit()
}

class PlayerInputAction

InputManager        "1..1"    .up.     "1..1"    InputEvents         : "Listens >"
InputManager        "1..1"    -down-   "0..*"    InputHandler        : "Has >"
InputManager        "1..1"    -down-   "1..1"    PlayerInputAction   : "Has >"

InputHandler        "1..1"    .down.   "1..1"    PlayerInputHandler  : "Inherits >"
InputHandler        "1..1"    .down.   "1..1"    PauseMenuInputHandler  : "Inherits >"
InputHandler        "1..1"    .down.   "1..1"    StoreMenuInputHandler  : "Inherits >"

@enduml
