@startuml inputsystem
class InputManager {
    {static} +Instance
    +PlayerInput
    --
    -enableActionMap()
    -disableActionMap()
}

class InputEventManager {
    ..Events..
    {static} +PauseAction
    {static} +ResumeAction
    {static} +EnableActionMap
    {static} +DisableActionMap
    --Invokers--
    +pause()
    +resume()
    +enableActionMap()
    +disableActionMap()
}

class PlayerInputHandler {
    +OnPause()
}

class PausedInputHandler {
    +OnResume()
}

class PlayerInputAction {

}

class InputController {
    +enableActionMap()
    +disableActionMap()
}

entity GameObject

class GameManager {
    {static} +Instance
    --
    -pauseGame()
    -resumeGame()
    -quitGame()
}


InputManager        "1..1    "   .up.    "1..1  "      InputEventManager    : "Listens >"
PlayerInputHandler  "1..1"       .up.    "1..1  "      InputEventManager    : "Invokes >"
PausedInputHandler  "1..1 "      .up.    "1..1"        InputEventManager    : "Invokes >"

InputManager        "1..1    "   -down-   "1..1"       PlayerInputAction    : "Has >"
PlayerInputHandler  "1..1"       .down.   "1..1    "   PlayerInputAction    : "Listens >"
PausedInputHandler  "1..1"       .down.   "1..1"       PlayerInputAction    : "Listens >"

InputController     "0..*"       .right.  "1..1"       InputEventManager    : "Invokes >"
InputController     "0..*"       -down-   "0..*"       GameObject           : "Has <"
GameManager         "1..1"       .left.   "1..1"       InputEventManager    : "Listens >"
@enduml
