@startuml pause
!theme reddress-darkblue

!include services/AudioSystem/AudioSystem.iuml
!include services/SceneSystem/SceneSystem.iuml
!include services/GameStateSystem/GameStateSystem.iuml
!include services/UISystem/UISystem.iuml
!include services/InputSystem/InputSystem.iuml

class PauseController {
    {static} +PauseGame()
    {static} +ResumeGame()
}
class PauseButtonController {
    +pauseGame()
    +resumeGame()
}

class GameObject

PauseController "1..1" .down. "1..1" IInputService     : "Implements >"
PauseController "1..1" .down. "1..1" IUIService        : "Implements >"
PauseController "1..1" .down. "1..1" IGameStateService : "Implements >"
PauseController "1..1" .down. "1..1" ISceneService     : "Implements >"
PauseController "1..1" .down. "1..1" IAudioService     : "Implements >"

PauseButtonController "0..*"   -down-   "0..1"   PauseController       : "Calls >"
GameObject            "0..*"   -down-   "0..1"   PauseButtonController : "Has >"

@enduml