@startuml scenesystem
class SceneLoader {
    {static} +Instance
    -bootScene
    --
    -loadScene()
    -unloadScene()
    -setSceneActive()
}

class SceneController {
    +loadScene()
    +unloadScene()
    +setSceneActive()
}

class AudioEventManager {
    ..Events..
    {static} +LoadScene
    {static} +UnloadScene
    {static} +SetSceneActive
    --Invokers--
    +loadScene()
    +unloadScene()
    +setSceneActive()
}

entity GameObject

SceneLoader       "1..1 "   .right.    "1..1"     AudioEventManager   : " Listens >"
SceneController   "0..*"    .up.       "1..1"     AudioEventManager   : " Invokes >"
SceneController   "0..*"    -left-     "0..*"     GameObject          : " Has <"
@enduml