@startuml scenesystem
class SceneLoader {
    {static} +Instance
    -bootScene
    --
    -loadScene()
    -unloadScene()
    -setSceneActive()
}

class SceneEvents {
    ..Events..
    {static} +OnLoadScene
    {static} +OnUnloadScene
    {static} +OnSetSceneActive
    --Invokers--
    {static} +loadScene()
    {static} +unloadScene()
    {static} +setSceneActive()
}

class SceneController {
    +loadScene()
    +unloadScene()
    +setSceneActive()
}
entity GameObject

SceneLoader       "1..1 "  .right.    "1..1"     SceneEvents   : " Listens >"
SceneController   "0..*"   .up.       "1..1"     SceneEvents   : " Invokes >"
SceneController   "0..*"   -left-     "0..*"     GameObject    : " Has <"
@enduml