@startuml store
!theme reddress-darkblue

!include services/audiosystem.iuml
!include services/scenesystem.iuml
!include services/gamestatesystem.iuml
!include services/uisystem.iuml
!include services/inputsystem.iuml

class StoreController {
    {static} +OpenStore()
    {static} +CloseStore()
}

class StoreButtonController {
    +openStore()
    +closeStore()
}

class GameObject

StoreController       "1..1"   .down.    "1..1"   InputEvents           : "Invokes >"
StoreController       "1..1"   .down.    "1..1"   UIEvents              : "Invokes >"
StoreController       "1..1"   .down.    "1..1"   GameStateEvents       : "Invokes >"
StoreController       "1..1"   .down.    "1..1"   SceneEvents           : "Invokes >"
StoreController       "1..1"   .down.    "1..1"   AudioEvents           : "Invokes >"

StoreButtonController "0..*"   -down-   "0..1"   StoreController       : "Calls >"
GameObject            "0..*"   -down-   "0..1"   StoreButtonController : "Has >"

@enduml