@startuml store
!theme reddress-darkblue

!include services/AudioSystem/AudioSystem.iuml
!include services/SceneSystem/SceneSystem.iuml
!include services/GameStateSystem/GameStateSystem.iuml
!include services/UISystem/UISystem.iuml
!include services/InputSystem/InputSystem.iuml

class StoreController {
    {static} +OpenStore()
    {static} +CloseStore()
}

class StoreButtonController {
    +openStore()
    +closeStore()
}

class GameObject

StoreController "1..1" .down. "1..1" IInputService     : "Implements >"
StoreController "1..1" .down. "1..1" IUIService        : "Implements >"
StoreController "1..1" .down. "1..1" IGameStateService : "Implements >"
StoreController "1..1" .down. "1..1" ISceneService     : "Implements >"
StoreController "1..1" .down. "1..1" IAudioService     : "Implements >"

StoreButtonController "0..*"   -down-   "0..1"   StoreController       : "Calls >"
GameObject            "0..*"   -down-   "0..1"   StoreButtonController : "Has >"
@enduml