@startuml transition
!theme reddress-darkblue

!include services/AudioSystem/AudioSystem.iuml
!include services/SceneSystem/SceneSystem.iuml
!include services/GameStateSystem/GameStateSystem.iuml
!include services/UISystem/UISystem.iuml
!include services/InputSystem/InputSystem.iuml

class TransitionController {
    {static} +StartGame()
    {static} +GoToMenu()
}
class TransitionButtonController {
    +startGame()
    +goToMenu()
}

class GameObject

TransitionController "1..1" .down. "1..1" IInputService     : "Implements >"
TransitionController "1..1" .down. "1..1" IUIService        : "Implements >"
TransitionController "1..1" .down. "1..1" IGameStateService : "Implements >"
TransitionController "1..1" .down. "1..1" ISceneService     : "Implements >"
TransitionController "1..1" .down. "1..1" IAudioService     : "Implements >"

TransitionButtonController "0..*" -down- "0..1" TransitionController       : "Calls >"
GameObject                 "0..*" -down- "0..1" TransitionButtonController : "Has >"

@enduml