@startuml uisystem
!theme reddress-darkblue

class UIEvents {
    ..Events..
    {static} +OnEnableCanvas
    {static} +OnDisableAllCanvases
    --Invokers--
    {static} +OnEnableCanvas
    {static} +OnDisableAllCanvases
}

class UIManager {
    -canvases
    ---
    -enableCanvases()
    -disableAllCanvases()
    ..Helpers..
    -getCanvas()
}

UIManager   "1..1"   .up.   "1..1"   UIEvents   : "Listens >"

@enduml