@startuml AudioManager
class AudioManager {
    {static} -instance
    -audioMixer
    ---
    -playAudio()
    -stopAudioClip()
    -stopAllAudioInGroup()
    -setVolume()
    -getAudioGroupPool()
    --Object Pooling--
    ..Pools..
    -menuAudioPool
    -gameAudioPool
    -musicAudioPool
    ..Pool Sizes..
    -menuAudioPoolSize
    -gameAudioPoolSize
    -musicAudioPoolSize
    ..Audio Prefabs..
    -menuAudioPrefab
    -gameAudioPrefab
    -musicAudioPrefab
}
@enduml