@startuml StoreSystem
!include StoreController.iuml
!include StoreButtonController.iuml
!include Store.iuml

Store                 "0..*" -down- "1..1" StoreController : "Calls >"
StoreButtonController "0..*" -down- "1..1" StoreController : "Calls >"
@enduml