@startuml GameFlow
!theme reddress-darkblue
skinparam linetype ortho 

!include MainState.puml
!include MainMenuState.puml

[*]       -down->  MainMenu
StartMenu -right-> Main
PauseMenu -left-> MainMenu

@enduml
