@startuml InputManager
class InputManager {
    {static} -instance
    -PlayerInput
    -playerInputHandler
    -pausedInputHandler
    --
    -enableActionMap()
    -disableActionMap()
}

class PlayerInputAction

InputManager "1..1" -down- "1..1" PlayerInputAction : "Has >"
@enduml